name: Release Apps

runs:
  using: "composite"
  steps:
    - name: 'Build'
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5
        path: ./Apps/${{ inputs.app_name }}
        command: 'python tactility.py build'
    - name: Download app artifacts
      uses: actions/download-artifact@v3
      with:
        path: downloaded_apps
    - name: Place reports' artifacts
      run: rsync -av downloaded_apps/*/*/ release_apps/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: "apps"
        path: release_apps/
        retention-days: 30
    - name: Output
      run: ls -R release_apps/
