name: Release Apps

runs:
  using: "composite"
  steps:
    - name: Download app artifacts
      uses: actions/download-artifact@v4
      with:
        path: downloaded_apps
    - name: Place reports' artifacts
      run: rsync -av downloaded_apps/*/*/ release_apps/
      shell: bash
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: "apps"
        path: release_apps/
        retention-days: 30
    - name: Output
      run: ls -R release_apps/
      shell: bash
